# Generated by Django 4.1 on 2022-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_hashtags_posthashtag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.UniqueConstraint(fields=('post', 'hashtag'), name='post_hashtag_constraint'),
        ),
    ]
